from typing import List, Dict

Song = Dict[str, object]

songs: List[Song] = [
    {
        "id": "en-1",
        "name": "Blinding Lights",
        "artists": ["The Weeknd"],
        "spotify_id": "0VjIjW4GlUZAMYd2vXMi3b",
        "album_name": "After Hours",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36",
        "release_date": "2020-03-20",
        "duration_ms": 200040,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b",
        "youtube_url": "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
        "popularity": 95,
        "genre": "pop",
        "mood": ["energetic", "party"],
        "language": "english",
        "energy": 0.93,
        "tempo": 171,
    },
    {
        "id": "en-2",
        "name": "Shape of You",
        "artists": ["Ed Sheeran"],
        "spotify_id": "7qiZfU4dY1lWllzX7mPBI3",
        "album_name": "÷ (Divide)",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96",
        "release_date": "2017-01-06",
        "duration_ms": 233713,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3",
        "youtube_url": "https://www.youtube.com/watch?v=JGwWNGJdvx8",
        "popularity": 94,
        "genre": "pop",
        "mood": ["romantic", "happy"],
        "language": "english",
        "energy": 0.75,
        "tempo": 96,
    },
    {
        "id": "en-3",
        "name": "Uptown Funk",
        "artists": ["Mark Ronson", "Bruno Mars"],
        "spotify_id": "32OlwWuMpZ6b0aN2RZOeMS",
        "album_name": "Uptown Special",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273e419ccba0baa8bd3f3d7abf2",
        "release_date": "2014-11-10",
        "duration_ms": 269667,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS",
        "youtube_url": "https://www.youtube.com/watch?v=OPf0YbXqDm0",
        "popularity": 92,
        "genre": "funk",
        "mood": ["party", "energetic", "happy"],
        "language": "english",
        "energy": 0.95,
        "tempo": 115,
    },
    {
        "id": "en-4",
        "name": "Someone Like You",
        "artists": ["Adele"],
        "spotify_id": "1zwMYTA5nlNjZxYrvBB2pV",
        "album_name": "21",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b2732118bf9b198b05a95ded6300",
        "release_date": "2011-01-24",
        "duration_ms": 285000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/1zwMYTA5nlNjZxYrvBB2pV",
        "youtube_url": "https://www.youtube.com/watch?v=hLQl3WQQoQ0",
        "popularity": 91,
        "genre": "pop",
        "mood": ["sad", "romantic"],
        "language": "english",
        "energy": 0.25,
        "tempo": 67,
    },
    {
        "id": "en-5",
        "name": "Bohemian Rhapsody",
        "artists": ["Queen"],
        "spotify_id": "7tFiyTwD0nx5a1eklYtX2J",
        "album_name": "A Night at the Opera",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273ce4f1737bc8a646c8c4bd25a",
        "release_date": "1975-10-31",
        "duration_ms": 354320,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/7tFiyTwD0nx5a1eklYtX2J",
        "youtube_url": "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",
        "popularity": 93,
        "genre": "rock",
        "mood": ["theatrical", "energetic"],
        "language": "english",
        "energy": 0.82,
        "tempo": 72,
    },
    {
        "id": "bn-1",
        "name": "Tum Hi Ho",
        "artists": ["Arijit Singh"],
        "spotify_id": "0kHpgMZkLuIDNWQlVS4yXH",
        "album_name": "Aashiqui 2",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273a75c2f26913099a420050f01",
        "release_date": "2013-04-08",
        "duration_ms": 262000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/0kHpgMZkLuIDNWQlVS4yXH",
        "youtube_url": "https://www.youtube.com/watch?v=Umqb9KENgmk",
        "popularity": 94,
        "genre": "romantic",
        "mood": ["sad", "romantic"],
        "language": "hindi",
        "energy": 0.2,
        "tempo": 64,
    },
    {
        "id": "bn-2",
        "name": "Kesariya",
        "artists": ["Arijit Singh"],
        "spotify_id": "3q2RTdOK1L4COA24jrdaxf",
        "album_name": "Brahmastra",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273decf7280a82f58780c48fb70",
        "release_date": "2022-06-15",
        "duration_ms": 213000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/3q2RTdOK1L4COA24jrdaxf",
        "youtube_url": "https://www.youtube.com/watch?v=8V5kIsZEJ0Q",
        "popularity": 92,
        "genre": "romantic",
        "mood": ["romantic", "dreamy"],
        "language": "hindi",
        "energy": 0.35,
        "tempo": 96,
    },
    {
        "id": "bn-3",
        "name": "Malang Sajna",
        "artists": ["Vishal Mishra"],
        "spotify_id": "5KbI9k1ghjXFwjGNVu7bvN",
        "album_name": "Dhoom 3",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b2738c4a44959bc4d31184f53bb3",
        "release_date": "2013-12-09",
        "duration_ms": 252000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/5KbI9k1ghjXFwjGNVu7bvN",
        "youtube_url": "https://www.youtube.com/watch?v=b8qXhpsRAvA",
        "popularity": 88,
        "genre": "bollywood",
        "mood": ["romantic", "dramatic"],
        "language": "hindi",
        "energy": 0.4,
        "tempo": 84,
    },
    {
        "id": "bn-4",
        "name": "Jai Ho",
        "artists": ["A. R. Rahman", "The Pussycat Dolls"],
        "spotify_id": "1dSrhA3pAJv7iyVGUa1ses",
        "album_name": "Slumdog Millionaire",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b27326df8d0fdf9f86b5e4d3b1eb",
        "release_date": "2008-10-16",
        "duration_ms": 255000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/1dSrhA3pAJv7iyVGUa1ses",
        "youtube_url": "https://www.youtube.com/watch?v=Jv5E_v1lFTs",
        "popularity": 89,
        "genre": "bollywood",
        "mood": ["energetic", "festive"],
        "language": "hindi",
        "energy": 0.9,
        "tempo": 128,
    },
    {
        "id": "en-6",
        "name": "Levitating",
        "artists": ["Dua Lipa"],
        "spotify_id": "39LLxExYz6ewLAcYrzQQyP",
        "album_name": "Future Nostalgia",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273bd26ede1ae69327010d49946",
        "release_date": "2020-03-27",
        "duration_ms": 203807,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/39LLxExYz6ewLAcYrzQQyP",
        "youtube_url": "https://www.youtube.com/watch?v=TUVcZfQe-Kw",
        "popularity": 91,
        "genre": "pop",
        "mood": ["happy", "party", "energetic"],
        "language": "english",
        "energy": 0.88,
        "tempo": 103,
    },
    {
        "id": "en-7",
        "name": "Bad Guy",
        "artists": ["Billie Eilish"],
        "spotify_id": "2Fxmhks0bxGSBdJ92vM42m",
        "album_name": "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b27350a3147b4edd7701a876c6ce",
        "release_date": "2019-03-29",
        "duration_ms": 194088,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m",
        "youtube_url": "https://www.youtube.com/watch?v=DyDfgMOUjCI",
        "popularity": 90,
        "genre": "pop",
        "mood": ["energetic", "dark"],
        "language": "english",
        "energy": 0.8,
        "tempo": 135,
    },
    {
        "id": "bn-5",
        "name": "Kala Chashma",
        "artists": ["Badshah", "Amaal Mallik"],
        "spotify_id": "1QvMUEYrR3wgFfBSV9JEeJ",
        "album_name": "Baar Baar Dekho",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273115b0d3afbb7b410dfb3e0f6",
        "release_date": "2016-09-09",
        "duration_ms": 234000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/1QvMUEYrR3wgFfBSV9JEeJ",
        "youtube_url": "https://www.youtube.com/watch?v=1V4XfH4vj0g",
        "popularity": 90,
        "genre": "bollywood",
        "mood": ["party", "energetic"],
        "language": "hindi",
        "energy": 0.92,
        "tempo": 128,
    },
    {
        "id": "bn-6",
        "name": "Zingaat",
        "artists": ["Ajay-Atul"],
        "spotify_id": "5fWHbRZBuh5uYM4TgB4ypP",
        "album_name": "Sairat",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273b1b2f161c0430e8526cfb043",
        "release_date": "2016-03-18",
        "duration_ms": 257000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/5fWHbRZBuh5uYM4TgB4ypP",
        "youtube_url": "https://www.youtube.com/watch?v=anlS2uq3PFM",
        "popularity": 89,
        "genre": "bollywood",
        "mood": ["party", "energetic"],
        "language": "hindi",
        "energy": 0.96,
        "tempo": 130,
    },
    {
        "id": "en-8",
        "name": "Thunder",
        "artists": ["Imagine Dragons"],
        "spotify_id": "1zB4vmk8tFRmM9UULNzbLB",
        "album_name": "Evolve",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b27375aa7f76f9a0e2f19b0b0f87",
        "release_date": "2017-06-23",
        "duration_ms": 187147,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/1zB4vmk8tFRmM9UULNzbLB",
        "youtube_url": "https://www.youtube.com/watch?v=fKopy74weus",
        "popularity": 87,
        "genre": "rock",
        "mood": ["energetic", "inspirational"],
        "language": "english",
        "energy": 0.86,
        "tempo": 105,
    },
    {
        "id": "bn-7",
        "name": "Ghungroo",
        "artists": ["Arijit Singh"],
        "spotify_id": "6VgK7prRrG79Z7SgAKh1Gc",
        "album_name": "War",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273e90a51d6469002919f7f3a10",
        "release_date": "2019-11-08",
        "duration_ms": 267000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/6VgK7prRrG79Z7SgAKh1Gc",
        "youtube_url": "https://www.youtube.com/watch?v=V1bFr2SWP1I",
        "popularity": 91,
        "genre": "bollywood",
        "mood": ["romantic", "dance"],
        "language": "hindi",
        "energy": 0.78,
        "tempo": 98,
    },
    {
        "id": "en-9",
        "name": "Counting Stars",
        "artists": ["OneRepublic"],
        "spotify_id": "2tpWsVSb9UEmDRxAl1zhX1",
        "album_name": "Native",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b27342284fb7dab2e0c82d0acf53",
        "release_date": "2013-03-22",
        "duration_ms": 257000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/2tpWsVSb9UEmDRxAl1zhX1",
        "youtube_url": "https://www.youtube.com/watch?v=hT_nvWreIhg",
        "popularity": 87,
        "genre": "pop",
        "mood": ["uplifting", "energetic"],
        "language": "english",
        "energy": 0.9,
        "tempo": 122,
    },
    {
        "id": "en-10",
        "name": "Shallow",
        "artists": ["Lady Gaga", "Bradley Cooper"],
        "spotify_id": "2VxeLyX666F8uXCJ0dZF8B",
        "album_name": "A Star Is Born",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b273e2d156fdc691f57900134342",
        "release_date": "2018-10-05",
        "duration_ms": 215733,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/2VxeLyX666F8uXCJ0dZF8B",
        "youtube_url": "https://www.youtube.com/watch?v=bo_efYhYU2A",
        "popularity": 88,
        "genre": "pop",
        "mood": ["romantic", "emotional"],
        "language": "english",
        "energy": 0.3,
        "tempo": 96,
    },
    {
        "id": "bn-8",
        "name": "Khalibali",
        "artists": ["Shreya Ghoshal", "Vishal Dadlani"],
        "spotify_id": "2XHNvzbdGAYO3nIuB8gpjE",
        "album_name": "Padmaavat",
        "album_cover": "https://i.scdn.co/image/ab67616d0000b2732f0a81a2f55c62b0f2ab0e9f",
        "release_date": "2018-01-25",
        "duration_ms": 262000,
        "preview_url": None,
        "spotify_url": "https://open.spotify.com/track/2XHNvzbdGAYO3nIuB8gpjE",
        "youtube_url": "https://www.youtube.com/watch?v=bYdFPR_2mFM",
        "popularity": 90,
        "genre": "bollywood",
        "mood": ["dramatic", "energetic"],
        "language": "hindi",
        "energy": 0.9,
        "tempo": 110,
    },
]

song_by_id = {song["id"]: song for song in songs}
